languageCode = "en"
languageName = "English"
weight = 1
title = "Gaowan Liang's Blog"
contentDir = 'content/en'

[params]
displayName = "EN"
isoCode = "en"
rtl = false
# logo = "img/avatar-circle.webp"
description = "My awesome blog"
# copyright = "Copy, _right?_ :thinking_face:"
dateFormat = "2 January 2006"

[params.author]
name = "Gaowan Liang"
image = "img/avatar.webp"
headline = "I'm curious !"
bio = "A person who keeps curious about everything"
links = [
  { link = "https://gwliang.com" },

  { github = "https://github.com/gaowanliang" },
  { x-twitter = "https://twitter.com/gaowanliang" },
]
