languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "高玩梁的博客"
contentDir = 'content/zh-cn'

[params]
displayName = "中文"
isoCode = "zh-cn"
rtl = false
# logo = "img/avatar-circle.webp"
description = "一个记录灵感的地方"
# copyright = "Copy, _right?_ :thinking_face:"
dateFormat = "2006年1月2日"

[params.author]
name = "高玩梁"
image = "img/avatar.webp"
headline = "我很好奇！"
bio = "一个对所有事物保持好奇心的人"
links = [
    { link = "https://gwliang.com" },

    { github = "https://github.com/gaowanliang" },
    { x-twitter = "https://twitter.com/gaowanliang" },
]
